add frontend in soncarcube

diff --git a/.github/workflows/github-action.yml b/.github/workflows/github-action.yml
--- a/.github/workflows/github-action.yml
+++ b/.github/workflows/github-action.yml
@@ -52,6 +52,42 @@ jobs:
            -F "file=@backend/bandit-report.json" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
 
+     
+      # ==== FRONTEND (React) ===
+     
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: npm
+          cache-dependency-path: frontend/package-lock.json
+
+      - name: Install frontend dependencies
+        working-directory: frontend
+        run: npm ci
+
+      - name: Lint frontend
+        working-directory: frontend
+        run: npm run lint || echo "⚠️ Lint warnings, but continuing"
+
+      - name: Run frontend tests
+        working-directory: frontend
+        run: npm test -- --watchAll=false || echo "⚠️ Tests failed, continuing build"
+
+      - name: Build frontend
+        working-directory: frontend
+        run: npm run build
+
+      - name: Upload frontend build artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: frontend-build
+          path: frontend/build
+
+     
+      # ==== SONARQUBE SCAN ====
+  
 
       - name: Run SonarQube Scan
         uses: SonarSource/sonarcloud-github-action@v2
@@ -62,7 +98,8 @@ jobs:
             -Dsonar.organization=drownedmilan
             -Dsonar.projectKey=DrownedMilan_time_manager
             -Dsonar.python.coverage.reportPaths=coverage.xml
-            -Dsonar.sources=backend/app
+            -Dsonar.sources=backend/app,frontend/src
+            -Dsonar.exclusions=**/node_modules/**,**/build/**
 
       - name: Send Discord Notification             # DISCORD NOTIF
         if: always()  # s’exécute même si le build échoue
